handshake-org/hnsd

configure.ac

Using the --with-network switch without an argument
as suggested in the install instructions,
has a default value of "yes" set by automake.
Consider that as a valid value for the
"testnet" case as well which is our intended default.

configure: fix with-network default case

---

src/dns.c

`hsk_dns_label_decode_tlsa` was never decoding the port properly. In fact, it the port's first character was `'0'`, it would enter an infinite loop.

dns: fix loop in hsk_dns_label_decode_tlsa

---

Makefile.am
README.md
configure.ac
src/addr.c
src/addr.h
src/addrmgr.c
src/addrmgr.h
src/daemon.c
src/ns.c
src/ns.h
src/platform-net.h
src/pool.c
src/pool.h
src/random.c
src/req.h
src/rs.c
src/rs.h
src/rs_worker.c
src/rs_worker.h
src/signals.c
src/signals.h
src/utils.c
src/utils.h

Support native Windows builds with Msys2/MinGW, using the MinGW libunbound package.
The major issue was that libunbound can't be hooked up to the libuv event loop with a file descriptor like on Unix (libunbound does not use a pipe on Windows, and libuv on Windows can only poll sockets anyway).
Instead, create a worker thread to operate libunbound, using libuv's threading primitives.  Results are queued back to the libuv event loop using a libuv async.
hnsd now shuts down cleanly on SIGINT and SIGTERM too, realized it was not doing this when I could not test the thread shutdown code.  This uncovered minor issues in the pool shutdown code, which are fixed.
The libunbound path can also be set when configuring, we're building libunbound from source in order to stay on the same version on all …

Windows support

---

src/brontide.c
src/ec.c
src/ec.h
src/secp256k1/elligator.h
src/secp256k1/elligator_impl.h
src/secp256k1/secp256k1.c

Adds Elligator Squared pubkey obfuscation to "Act One" of the Brontide handshake. Crypto code is imported from bcrypto and exposed to the brontide module. 
References:
https://github.com/handshake-org/hsd/commit/e0a2f7b35ccbd9e7406db14b7fa3756941dbd4e3

Mainnet 2/4: Elligator

---

src/addr.c
src/addrmgr.c
src/pool.c
src/pool.h

Replaces #35
We have no test suite so I'm just trying to launch with different combinations of params that crashed or didn't work before this PR. Closing hnsd is the only way to get a quick list of connected peers :-(
Testing:
```
chain (0): chain is fully synced
addrman: added addr: 165.22.151.242:44806
addrman: added addr: 172.104.214.189:44806
addrman: added addr: 173.255.209.126:44806
addrman: added addr: 172.104.177.177:44806
addrman: added addr: 139.162.183.168:44806
addrman: added addr: 74.207.247.120:44806
addrman: added addr: 45.79.134.225:44806
pool: seed address exceeds maximum length allowed.
pool: pool opened (size=8)
...
```
```
chain (0): chain is fully synced
addrman: added addr: 165.22.151.242:44806
addrman: added addr: 172.104.214.189:44806
addrman: added addr: …
```

pool: handle both clearnet and brontide peers + clearnet peer discovery

---

Makefile.am
README.md
configure.ac
man/hnsd.1
src/constants.h
src/daemon.c

I had to a search-and-replace for this, probably could be automated for future versions.
Hoping I didn't miss anything!
🚀  very excited to release!

pkg: bump version to 1.0.0 and remove mainnet warning

---

src/ec.h

An implicit declaration was blocking builds on macs with clang 12 and creatinng warnings on all platforms.  
This resolves that issue by importing elligator.h in ec.h  ﻿

fixed implicit declaration by importing elligator.h to ec.h

---

Makefile.am
README.md

This change allows one to do `sudo make install` and get the `hnsd` binary in a standard installation directory.
`noinst_PROGRAMS` seems like it was explicitly disabled but I don't know the reasoning.
This change will allow package managers like AUR to install the binary  (currently it does not)
https://aur.archlinux.org/packages/hnsd-git/
Tagging @Thann who maintains the AUR package.

makefile: install hnsd

---

src/pool.c

This PR fixes a frequent crash on windows whenever a connection resets with error -4077. This crash should technically happen on other OSs but I've only noticed it frequently on windows.
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffb1ceb43cf in msvcrt!memmove () from C:\Windows\System32\msvcrt.dll
(gdb) bt
#0  0x00007ffb1ceb43cf in msvcrt!memmove ()
from C:\Windows\System32\msvcrt.dll
#1  0x00007ff6bf897801 in hsk_peer_on_read (peer=0x1b68af72ee0,
data=<optimized out>, data_len=<optimized out>) at src/pool.c:1603
#2  0x00007ff6bf898206 in hsk_peer_on_read (data_len=18446744073709547539,
data=<optimized out>, peer=0x1b68af72ee0) at src/pool.c:1595
#3  after_read (stream=<optimized out>, nread=-4077, buf=<optimized out>)
at src/pool.c:1818
#4  0x00007ff6bf8d0f51 in …
```

pool: check for errors in after_read before using the buffer

---

src/ns.c

Fixes a bug in https://github.com/handshake-org/hnsd/pull/67 where I re-used a variable name `synth` for both a string and a flag indicating whether or not we should cache a response.

ns: fix caching and not-caching synth records

---

src/msg.c

This addresses the issue in #56 with the hnsd receiving lots of "unknown command" messages which turn out to be transaction inventory messages. We disable transaction relay (using version flag) and cut down on these since we won't be relaying them anyway.

version: set no_relay true and ignore tx invs

---

src/dns.c
src/resource.c

This is also logged in #45 by @pinheadmz and happens in `ns.c - after_resolve` as mentioned in the logs:
```
==262390== 2,628,352 bytes in 10,267 blocks are definitely lost in loss record 21 of 21
==262390==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==262390==    by 0x12876F: hsk_dns_txt_alloc (dns.c:2075)
==262390==    by 0x137B73: hsk_txt_record_read (resource.c:144)
==262390==    by 0x137F27: hsk_record_read (resource.c:376)
==262390==    by 0x1380BB: hsk_resource_decode (resource.c:436)
==262390==    by 0x1221C0: after_resolve (in /home/pinheadmz/Desktop/work/hnsd/hnsd)
==262390==    by 0x133FEB: hsk_peer_handle_proof (pool.c:1525)
==262390==    by 0x133FEB: hsk_peer_handle_msg (pool.c:1584)
==262390==    by 0x133FEB: …
```

Fix hsk_dns_txt leaks

---

src/cache.c

This is next memleak found with `make CFLAGS=-fsanitize=leak` and fixes another
leak logged in https://github.com/handshake-org/hnsd/issues/45 by @pinheadmz.
It's highly likely to be related to this:
```
==262390== 73,597 bytes in 294 blocks are definitely lost in loss record 18 of 21
==262390==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==262390==    by 0x12B315: hsk_dns_msg_encode (dns.c:178)
==262390==    by 0x120CC3: hsk_cache_insert (in /home/pinheadmz/Desktop/work/hnsd/hnsd)
==262390==    by 0x1222E8: after_resolve (in /home/pinheadmz/Desktop/work/hnsd/hnsd)
```
You can replicate it with sanitizer this way:
- `make CFLAGS=-fsanitize=leak`
- `./hnsd -r 127.0.0.1:1553`
- wait for some time to sync (I just wait til 10k)
- `dig …

Cache memleak

---

src/daemon.c
src/pool.c
src/pool.h

Usage:
```
./hnsd -a bacon
./hnsd --user-agent bacon
```
Result (from hsd):
```
--> hsd-rpc getpeerinfo
[
{
"id": 13,
"addr": "127.0.0.1:64061",
"addrlocal": "127.0.0.1:10000",
"services": "00000000",
"servicenames": [],
"relaytxes": false,
"lastsend": 1639587864,
"lastrecv": 1639587864,
"bytessent": 35343,
"bytesrecv": 249,
"conntime": 1,
"timeoffset": 0,
"pingtime": -1,
"minping": -1,
"version": 1,
"subver": "/hnsd:1.0.0/bacon",
"inbound": true,
"startingheight": 0,
"besthash": "0000000000000000000000000000000000000000000000000000000000000000",
"bestheight": -1,
"banscore": 0,
"inflight": [],
"whitelisted": false
}
]
```

daemon/pool: allow user to set supplemental user agent string

---

src/daemon.c
src/pool.c

https://github.com/handshake-org/hnsd/blob/d2bb5f4c77c2cb2aba18be7c57ce6ffe9abca821/src/pool.c#L309-L312
strcat will put `\0` byte outside allocated memory when passed string with length `255-12`
(12 -/hnsd:1.0.0/ length).
It did not crash, but still.
This will be command if you want to replicate issue:
```sh
./hnsd -a `node -e 'console.log("a".repeat(255 - 12))'` # Just run with aaaa...
gdb --args ./hnsd -a `node -e 'console.log("a".repeat(255 -12))'` # Gdb to check memory
```
I noticed that daemon would segfault if the user agent check failed (`hsk_pool_set_agent`).
Reproduce with:
```sh
./hnsd -a `node -e 'console.log("a".repeat(255))'` 
```
The reason it fails is the fail label in the `hsk_daemon_init` that calls `hsk_daemon_after_close`.
`hsk_daemon_after_close`(this is basically …

Daemon separate close and free

---

.github/workflows/test-windows.yaml
.github/workflows/test.yml
.gitignore
Makefile.am
README.md
integration/package-lock.json
integration/package.json
integration/test-util.js
integration/test/sync-resolve-test.js
src/constants.h
src/daemon.c
test/base32-test.c
test/hnsd-test.c
test/hnsd-test.h
test/resource-test.c

Closes #23 
This cleans up the framework for unit tests (written C and compiled into executable `test_hnsd`) and also introduces a new integration test system using nodejs and hsd.
```
--> ./test_hnsd
Testing hnsd...
test_base32
test_base32_encode_decode
test_resource
test_resource_pointer_to_ip
ok
--> cd integration/
--> npm run test
> hnsd_integration_test@1.0.0 test
> bmocha --reporter spec test/*.js
Basic sync & resolve
✓ should register names and sync (845ms)
✓ should resolve DS
✓ should resolve NS
✓ should resolve TXT
✓ should resolve GLUE4 without glue
✓ should resolve GLUE4 with glue
✓ should resolve GLUE6 without glue
✓ should resolve GLUE6 with glue
✓ should resolve SYNTH4 with glue
✓ should resolve SYNTH6 with glue
10 passing (953ms)
```

Organize unit tests and add integration tests with hsd

---

Makefile.am
docs/hesiod.md
integration/test-util.js
integration/test/hesiod-test.js
src/chain.c
src/chain.h
src/constants.h
src/dns.c
src/hesiod.c
src/hesiod.h
src/ns.c
src/pool.c
src/pool.h
src/utils.c
test/base32-test.c
test/dns-test.c
test/hnsd-test.c
test/hnsd-test.h
test/resource-test.c

Built on top of https://github.com/handshake-org/hnsd/pull/101 waiting for review and merge
See original idea in https://github.com/handshake-org/hsd/issues/443
The HS API can be thought of like a single JSON object:
```
.: {
hnsd: {
chain: {
tip: {
hash:   `32 byte hex string`,
height: `unsigned int`,
time:   `unsigned int`
},
synced:   `boolean`,
progress: `float`
},
pool: {
size:     `unsigned int`,
[id].peers: [
{
host:  `string`,
agent: `string`,
headers `unsigned int`,
proofs: `unsigned int`,
state: `string`
}
]
}
}
}
```
The object properties and sub-objects are addressed like a sort of backwards JSON notation, with an implied "wildcard" (`*`) prepended to the query string. So querying `sub.domain.` is equivalent to querying `*.sub.domain` and all the data at or below that level …

Introduce Hesiod (class HS) metadata resolver

---

.github/workflows/memory-sanitizer.yaml
.github/workflows/test.yml
Makefile.am
configure.ac
integration/test-util.js
integration/test/config-test.js
src/pool.c
src/pool.h

Closes #104 
Built off https://github.com/handshake-org/hnsd/pull/99 which fixes some memory leaks.
This PR adds a flag `configure --with-sanitizers=<sanitizers>` where `<sanitizers>` is a comma separated list of sanitizers like `address,leak`. I borrowed the configure logic from Bitcoin Core: https://github.com/bitcoin/bitcoin/blob/38d06e1561013f4ca845fd5ba6ffcc64de67f9c0/configure.ac#L315-L319
The flag is added to CI integration tests. I intentionally committed a few memory violations and then patched them to demonstrate to reviewers how this will look (it's a bit of a mess, but works by throwing errors in the bmocha suite).
example memory leak detected: https://github.com/handshake-org/hnsd/actions/runs/3527082949/jobs/5915748956#step:8:645
example use-after-free detected: …

ci: build with sanitizer to check for memory issues

---

README.md

To stop confusion with `unbound` and `libunbound-dev` this adds the apt install script.

Add Linux dependencies install script

---

.github/workflows/docker.yaml
.github/workflows/test-windows.yaml
.github/workflows/test.yml

The images will be published to [ghcr.io](https://github.com/handshake-org/hnsd/packages) and [docker hub](https://hub.docker.com/r/handshakeorg/hnsd).
Each new git tag will generate/replace:
Example tag: `v1.2.3`
* handshake-org/hnsd:latest
* handshake-org/hnsd:1.2.3
* handshake-org/hnsd:1.2
* handshake-org/hnsd:1
Merges to `master` generates:
* handshake-org/hnsd:edge

Add Docker workflow for building and pushing images
